define([
	'./unit/buildContentItem',
	'./unit/buildLinkString',
	'./unit/compileHeadingTags',
	'./unit/findHeadingTags',
	'./unit/findIncludeTags',
	'./unit/parseIncludeTag',
	'./unit/parseHeadingTag',
	'./unit/processFile',
	'./unit/processIncludeTags',
	'./unit/replaceIncludeTags',
	'./unit/writeFile'
]);